### PR TITLE
Made the Colour Styles Strict for avoiding the colour overriding on Build Process on angular 5 Projects

### PR DESCRIPTION
**Pull request by riginoommen**
…he build process

### CODE REVIEW

**Comment by scttcper** [comment]
Why? Are the colors being overridden somehow?

**Comment by riginoommen** [comment]
I am using this module on my new project then on the build process css will be overridden for avoiding it we contributing to this change

**Comment by yarrgh** [comment]
I still don't understand why this is needed. The styles are meant to be overridden if needed/wanted by the end user. You should adjust your build process to not override the css.

You could also take the css classes and rename them to something unique that won't be overridden and then tell ngx-toastr about it in the `forRoot()`

**Comment by scttcper** [comment]
Not going to merge this into the project as I don't think it fits most people's use case.

**Pull request closed without merging**
