### PR TITLE
feat: better duplicate detection #525 #501

### LINKED ISSUE #525: preventDuplicates will prevent Error toasts if Warnings with the same message exist
Steps to reproduce:
1. Set preventDuplicates = true
2. Create a warning toast like "Server did not respond. Please try again."
3. Create an error toast with the same message
4. Error toast will not appear.

### PR DESCRIPTION
**Pull request by yutamago**
Fixes #525 and #501 by only detecting a duplicate if the title, message and type are equal to those of an existing active toast.

### CODE REVIEW

**Comment by ArielLeslie** [comment]
Are there any plans to merge this change? Duplicates based on title + message would be a useful improvement.

**Comment by scttcper** [comment]
@ArielLeslie this is a breaking change that would need to wait for a major version. I think communication of the new behavior would have to be very clear as it could be surprising to some. The existing duplicate detection is implemented the same way the original vanilla js toastr worked.

**Comment by pdemilly** [comment]
What about using the toastId as a reference instead. So we could update a toast if it is still present on the screen or show a new one if not. Also could be used to update the progress bar instead of displaying one that is limited to time

**Comment by scttcper** [comment]
this would have to be re-written with the count duplicates feature and even then i'm not sure

**Pull request closed without merging**
