### PR TITLE
new svg icons

### LINKED ISSUE #281: support high resolution on images
Hello, first of all thank you great job!
I have a request about notification images, they seem to be in low resolution :(
I think it should convert to base64 images with a size of at least 256x256 or 512x512
On retina screen or other high dpi screen it's not far from being ugly :)

### PR DESCRIPTION
**Pull request by scttcper**
this uses font awesome's new 5.0 "regular" weight icons. Before they were base64 encoded images and now they'd be base64 encoded svg. The biggest change would be the error icon not being a shield and the info. closes #281

old:
screen shot 2017-12-05 at 11 34 23 am
new:
screen shot 2017-12-05 at 3 40 01 pm

### CODE REVIEW

**Comment by yarrgh** [comment]
Icons look more consistent as well

**Comment by scttcper** [comment]
Looks like i don't needs to base64 encode and can instead do 
```
url('data:image/svg+xml;utf8,<svg xmlns="..."></svg>
```

**Comment by yarrgh** [comment]
I think it is cleaner to keep it base64 encoded. That's just my opinion though.

**Comment by scttcper** [comment]
I agree clean, but its quite the process to change the color of the fill and then re-encode and i think we'd get fewer questions. Just tell them to replace the svg with the desired svg.

**Comment by yarrgh** [comment]
It's actually not as ugly as I thought it would be. Plus, it decreases the size more than base64 encoding is easier to replace, if needed. Win-win if you ask me.

**Comment by yarrgh** [comment]
With using the svg, in the latest firefox version, 57.0.1, the icons don't show up. But do in Chrome 62.

**Comment by scttcper** [comment]
damn

**Comment by yarrgh** [comment]
Might be a bug though? Works in Chrome and Microsoft Edge (surprisingly)

**Comment by scttcper** [comment]
XML Parsing Error: unclosed token

**Comment by scttcper** [comment]
fixed for firefox. looks like i read it wrong now that fontawesome 5 is public. The "regular" weight icons can't be redistributed. Would have to use the "solid" ones. https://fontawesome.com/icons/check?style=solid

**Comment by scttcper** [comment]
I've updated the images in the PR with the "solid" icons. I think its still a good fit. https://fontawesome.com/license

**Comment by yarrgh** [comment]
Looks good to me

**Comment by yarrgh** [comment]
Although it isn't a huge update, and most may not notice the new success icon, should the README.md be updated with the new icon?

**Comment by scttcper** [comment]
opened a new PR

**Pull request closed without merging**
