### PR TITLE
switch to changedetectorref 

### LINKED ISSUE #226: onActivateTick can cause infinite loops
My use case is a custom error handler showing toasts:

```
export class ToastErrorHandler extends ErrorHandler {
  constructor(private injector: Injector) {
    super();
  }

  handleError(error: Error): void {
    const toastr = this.injector.get(ToastrService);

    const config: Partial<IndividualConfig> = {
      timeOut: 10000
    };

    toastr.error(error.message, config);

    super.handleError(error);
  }
}
```

Obviously this toast won't show as expected, because the error handler runs outside angular's zone (for good reason).
Using `onActivateTick` seems tempting, but `tick()` triggers change detection on the entire component tree. If the handled error is raised during change detection, it will be raised again and again and freeze the browser tab.

I'm pretty sure that calling `appRef.tick()` is overkill in any scenario, because what we actually need is change detection inside the toast: `toastr.error('blah').portal.changeDetectorRef.detectChanges();`

Toasts should run CD on themselves when necessary instead of relying on ticks.

### PR DESCRIPTION
**Pull request by scttcper**
closes #226

This would probably have to be a major version bump since it could break everyone extending the toast component. I'm also not sure that this is what we want. @yarrgh

### CODE REVIEW

**Comment by scttcper** [comment]
@yarrgh I'm a fan of that.

**Comment by yarrgh** [comment]
@scttcper will you review the changes I just made to this pull request? It implements the suggestion I made earlier. 

From my testing this should also fix #267. I recreated the error handler and caused an error on template parsing (accessing a property of an undefined variable).

**Comment by scttcper** [comment]
Yeah I like this method. Just going to change the rxjs operator to the 5.5.0 lettable import.

**Comment by scttcper** [comment]
@yarrgh Do we need take? Its only fired once and then completed.

**Comment by yarrgh** [comment]
If it's fired once and completed, then no. The completion would clean up the subscription.

**Pull request merged**
